services:
  go:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./config:/config:ro
      - ./doc:/doc:rw
    ports:
      - 8989:80
    networks:
      default:
        aliases:
          - chargepoint-api
#    command: ["/server", "--seed"]

  postgres:
    image: postgis/postgis:18-3.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'cpuser'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: chargepoint_db
    volumes:
      - postgresdb:/var/lib/postgresql

volumes:
  postgresdb:
